Clear-Host
Write-Host "--- Lab Workstation Report ---" -ForegroundColor Cyan
Write-Host "------------------------------"

# Get current date
$currentDate = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
Write-Host "Timestamp:    $currentDate"

# Get computer name
$compName = $env:COMPUTERNAME
Write-Host "Workstation:  $compName"

# Get current user
$currentUser = $env:USERNAME
Write-Host "Student User: $currentUser"

Write-Host "------------------------------"
Write-Host "Report generation complete." -ForegroundColor Green
# SIG # Begin signature block
# MIIFpgYJKoZIhvcNAQcCoIIFlzCCBZMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCDjMii3POL+O73p
# oRG8lLGq1BbT3VWSVKJyGpu5DUKSyKCCAx4wggMaMIICAqADAgECAhBAAeiJKNWW
# hkGmM7mXswZCMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNVBAMMDUxhYkluc3RydWN0
# b3IwHhcNMjUxMjAyMTYxNDA3WhcNMjYxMjAyMTYzNDA3WjAYMRYwFAYDVQQDDA1M
# YWJJbnN0cnVjdG9yMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Ky7
# BAzAzkJaIF2XFGC562nqZat1aqGoQC9jMn3mi2heJn39oBFR6yq4L9MRgvpTDMq+
# wacfyP5LdJBXk8H7WXO6u+7VlEwXU+UFSNfjMYET8oORZ0N+RvSDPburX1/Pvmil
# xAs3hdSnT9q7soSAeaF7B5HoaqKCguKAxXLeo3lRATz4CcJHjFg2Db1WZdohhLNA
# idCaoEogPcpDc6yYR4K3OH/5bmvajFxAaODC0esvsx8YZuWlurZH99yhL16AQes7
# 8hCGSDTqQJqQHBDnVf4pdy34cDrSf5tYzZmdiXvVJdTCMpARTHlH+ojC7F3GFJdR
# /L1dNGPOiFlUDItYtQIDAQABo2AwXjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwGAYDVR0RBBEwD4INTGFiSW5zdHJ1Y3RvcjAdBgNVHQ4EFgQU
# S9mpX28ThPXjEPZn1p5D2g3QTUYwDQYJKoZIhvcNAQELBQADggEBAGqGy1tHWpXr
# FVSTO9n6SCNc0kF966d2Yhg1Woja//5MS+EXooBG+rzrN2LxpO6R4BH9nX3cv03A
# kFfzf20GIKw83QRS/7mB9/bMjrfvkfi4Q9fElG4Fwbyb1zIxFdoB7o7OBoxHeMvM
# dvFZ95XsPi8ohs8YV3HZY8DdJJAEiLHppOQwljW1aSm6YsKHwfsAo3N+/Y9vyfJW
# 6zUUHHL7qlDIsQQwCsmEKdxf257P+eKeWm2Kp6FihnNexxjMceavqMg8d1lN4In3
# pcflfX2hn7Qq1gCM7zrVcfOSysLQmtW0NgqjdUMXzFObCN4a+R5S8MK5LsNZMiui
# LWN3hPWuUD4xggHeMIIB2gIBATAsMBgxFjAUBgNVBAMMDUxhYkluc3RydWN0b3IC
# EEAB6Iko1ZaGQaYzuZezBkIwDQYJYIZIAWUDBAIBBQCggYQwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQgptbP4OK2A4PH
# rCbfsAfwQBQfXy4dbgkU+85Yhvp0tNUwDQYJKoZIhvcNAQEBBQAEggEAyHAiCyN9
# rxpdwHniteg/GqKjpFaep35VqiL2g5P4Y4ObQVaiTUoto8cCnhLt9lPDMA7T1EYV
# BRzsksemXwV/2hWBgaJys90CKNZhcX8RgxTs54C3d0aNS1W2qUxXTHkjuMtD3+hD
# 81HvTgjEi7/FzWkYTQSVBHP1JSLwqZ/doFLIKwOjkozMzZA5yXD8lKPeLLWYR8IG
# fNUvF5qog2I04MXcd/XQ6hLKwVb9byPEAZFJSMwM8HeqXoV1rYLmqMKrCnjGZO/Y
# V4IK3zOMS16ZEtkwhTuoM4nlLBodcs0O8kvXSKEQJBjwI9WkED20ZJz4y6nHEO4L
# s6IfsFG6vHEFig==
# SIG # End signature block
