Clear-Host

# Ask the student for their name
$studentName = Read-Host -Prompt "Please enter your name"

# Check if the input is empty
if ([string]::IsNullOrWhiteSpace($studentName)) {
    Write-Host "You didn't enter a name, but welcome to the lab anyway!" -ForegroundColor Yellow
}
else {
    Write-Host "Hello, $studentName! Welcome to the Code Signing Lab." -ForegroundColor Cyan
}


Start-Sleep -Seconds 2
# SIG # Begin signature block
# MIIFpgYJKoZIhvcNAQcCoIIFlzCCBZMCAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCnyMkkEo5Q1ZxR
# hMBDBTF+9FFQXm+v3HK5h3w/P+eHI6CCAx4wggMaMIICAqADAgECAhBAAeiJKNWW
# hkGmM7mXswZCMA0GCSqGSIb3DQEBCwUAMBgxFjAUBgNVBAMMDUxhYkluc3RydWN0
# b3IwHhcNMjUxMjAyMTYxNDA3WhcNMjYxMjAyMTYzNDA3WjAYMRYwFAYDVQQDDA1M
# YWJJbnN0cnVjdG9yMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0Ky7
# BAzAzkJaIF2XFGC562nqZat1aqGoQC9jMn3mi2heJn39oBFR6yq4L9MRgvpTDMq+
# wacfyP5LdJBXk8H7WXO6u+7VlEwXU+UFSNfjMYET8oORZ0N+RvSDPburX1/Pvmil
# xAs3hdSnT9q7soSAeaF7B5HoaqKCguKAxXLeo3lRATz4CcJHjFg2Db1WZdohhLNA
# idCaoEogPcpDc6yYR4K3OH/5bmvajFxAaODC0esvsx8YZuWlurZH99yhL16AQes7
# 8hCGSDTqQJqQHBDnVf4pdy34cDrSf5tYzZmdiXvVJdTCMpARTHlH+ojC7F3GFJdR
# /L1dNGPOiFlUDItYtQIDAQABo2AwXjAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwGAYDVR0RBBEwD4INTGFiSW5zdHJ1Y3RvcjAdBgNVHQ4EFgQU
# S9mpX28ThPXjEPZn1p5D2g3QTUYwDQYJKoZIhvcNAQELBQADggEBAGqGy1tHWpXr
# FVSTO9n6SCNc0kF966d2Yhg1Woja//5MS+EXooBG+rzrN2LxpO6R4BH9nX3cv03A
# kFfzf20GIKw83QRS/7mB9/bMjrfvkfi4Q9fElG4Fwbyb1zIxFdoB7o7OBoxHeMvM
# dvFZ95XsPi8ohs8YV3HZY8DdJJAEiLHppOQwljW1aSm6YsKHwfsAo3N+/Y9vyfJW
# 6zUUHHL7qlDIsQQwCsmEKdxf257P+eKeWm2Kp6FihnNexxjMceavqMg8d1lN4In3
# pcflfX2hn7Qq1gCM7zrVcfOSysLQmtW0NgqjdUMXzFObCN4a+R5S8MK5LsNZMiui
# LWN3hPWuUD4xggHeMIIB2gIBATAsMBgxFjAUBgNVBAMMDUxhYkluc3RydWN0b3IC
# EEAB6Iko1ZaGQaYzuZezBkIwDQYJYIZIAWUDBAIBBQCggYQwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQg97MIovK0wa1R
# I73VzhNHNJKXORk1/LhoJ0FmKV2SCVQwDQYJKoZIhvcNAQEBBQAEggEAMzRT5fyH
# BbiiLhJkoecZzJWbnBcXgbUVq9IRWNU/yubEkHXsDY3mYGA5i+cA27Gm/RAM1pXa
# kCxNfs4uwrX0q41TaiETZIafdG1qI9PkGxTdKVqBTDTZwYbcusxOc4Z/lWQF9WDj
# YgSKgAL9n3JqhTkQGXnrsquySxBzze+w5EBwxfwgkXdWXSmTgiJP4eim1aSJ+32N
# GgCbsEa+0uSaxdzxwF+Q3iEtwmcTKqlW3YVacgysk0ViEzgcdtM1xXRCKJX5rEvV
# Pc2dUfq/h4vSFFf6PEqMDHIHYqN4duDEVVQkwDUEnvjBXrsZZBt0vt0X3eejF7HQ
# UR+peV8yvXznIw==
# SIG # End signature block
